ParagonRCC-MVC3/ParagonRCC-MVC3/Models/Mapping.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Xml.Linq;

namespace ParagonRCC_MVC3.Models
{
    public class Mapping
    {
        public int Id;
        public string Name;
        public int Order;
        public List<Condition> Conditions = new List<Condition> { };
        public List<Transform> Transforms = new List<Transform> { };

        public Mapping() { }

        public Mapping(XElement el)
        {
            if (el.Attribute("id") != null)
                int.TryParse(el.Attribute("id").Value, out this.Id);
            else
                throw new ArgumentException(string.Format("element {0} does not have an 'id' attribute, or the attribute is not a number.", el.ToString()));
            if (el.Attribute("order") != null)
                int.TryParse(el.Attribute("order").Value, out this.Order);
            else
                throw new ArgumentException(string.Format("element {0} does not have an 'order' attribute, or the attribute is not a number.", el.ToString()));
            if (el.Attribute("name") != null)
                this.Name = el.Attribute("name").Value;
            else
                throw new ArgumentException(string.Format("element {0} does not have a 'name' attribute.", el.ToString()));
            Conditions.AddRange(Condition.FromElements(el.Elements("condition")));
            Transforms.AddRange(Transform.FromElements(el.Elements("transform")));
        }
        
        public static List<Mapping> FromXml(string xml)
        {
            if (string.IsNullOrEmpty(xml))
                xml = @"<mappings><mapping id='1' order='1' name='default'></mapping></mappings>";
            List<Mapping> rv = new List<Mapping>();
            try
            {
                XElement root = XElement.Parse(xml);
                rv.AddRange(root.Elements("mapping").Select(e => new Mapping(e)));
            }
            catch (Exception ex)
            {
                ex.ToString();
            }

            return rv;
        }
    }
}

ParagonRCC-MVC3/ParagonRCC-MVC3/Controllers/MappingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ParagonRCC_MVC3.Models;

namespace ParagonRCC_MVC3.Controllers
{
    public class MappingController : Controller
    {
        //
        // GET: /Mapping/

        public ActionResult Index(int robotId, int serverId)
        {
            var server = ParagonRCC_MVC3.Models.Server.Servers.Where(s => s.Id == serverId).SingleOrDefault();
            if (null == server)
                return new HttpNotFoundResult();
            var robot = server.Robots.Where(r => r.Id == robotId).SingleOrDefault();
            if (null == robot)
                return new HttpNotFoundResult();
            
            ViewBag.RobotId = robotId;
            ViewBag.ServerId = serverId;

            if (Request.IsAjaxRequest())
                return PartialView(robot.Mapping);
            return View(robot.Mapping);
        }

        //
        // GET: /Mapping/Details/5

        public ActionResult Details(int id, int robotId, int serverId)
        {
            var server = ParagonRCC_MVC3.Models.Server.Servers.Where(s => s.Id == serverId).SingleOrDefault();
            if (null == server)
                return new HttpNotFoundResult();
            var robot = server.Robots.Where(r => r.Id == robotId).SingleOrDefault();
            if (null == robot)
                return new HttpNotFoundResult();
            //var item = robot.Mappings.Where(m => m.Id == id).SingleOrDefault();
            //if (null == item)
            //    return new HttpNotFoundResult();
            object item = null;

            ViewBag.RobotId = robotId;
            ViewBag.ServerId = serverId;
            ViewBag.MappingId = id;

            if (Request.IsAjaxRequest())
                return PartialView(item);
            return View(item);
        }

        //
        // GET: /Mapping/Create

        public ActionResult Create(int robotId, int serverId)
        {
            var server = ParagonRCC_MVC3.Models.Server.Servers.Where(s => s.Id == serverId).SingleOrDefault();
            if (null == server)
                return new HttpNotFoundResult();
            var robot = server.Robots.Where(r => r.Id == robotId).SingleOrDefault();
            if (null == robot)
                return new HttpNotFoundResult();
            var item = new Mapping();
            if (null == item)
                return new HttpNotFoundResult();

            ViewBag.RobotId = robotId;
            ViewBag.ServerId = serverId;

            if (Request.IsAjaxRequest())
                return PartialView(item);
            return View(item);
        } 

        //
        // POST: /Mapping/Create

        [HttpPost]
        public ActionResult Create(string name, int robotId, int serverId)
        {
            try
            {
                if (string.IsNullOrEmpty(name))
                    throw new ArgumentNullException("newName");
                var server = ParagonRCC_MVC3.Models.Server.Servers.Where(s => s.Id == serverId).SingleOrDefault();
                if (null == server)
                    return new HttpNotFoundResult();
                var robot = server.Robots.Where(r => r.Id == robotId).SingleOrDefault();
                if (null == robot)
                    return new HttpNotFoundResult();
                //int newId = robot.Mappings.Max(m => m.Id) + 1;
                //var mapping = new Mapping() { Id = newId, Name = name, Order = newId, Transforms = new List<Transform>(), Conditions = new List<Condition>() };
                //robot.Mappings.Add(mapping);
                Mapping mapping = null;
                if (Request.IsAjaxRequest())
                {
                    Response.AddHeader("Location", Url.Action("Details", new { id = mapping.Id, robotId = robotId, serverId = serverId }));
                    return new HttpStatusCodeResult(299, "Created");
                }
                return RedirectToAction("Details", new { id = mapping.Id, robotId = robotId, serverId = serverId });
            }
            catch
            {
                if (Request.IsAjaxRequest())
                    return new HttpStatusCodeResult(400, "name cannot be null or empty");
                return View();
            }
        }

        public ActionResult Edit(int id, int robotId, int serverId)
        {
            var server = ParagonRCC_MVC3.Models.Server.Servers.Where(s => s.Id == serverId).SingleOrDefault();
            if (null == server)
                return new HttpNotFoundResult();
            var robot = server.Robots.Where(r => r.Id == robotId).SingleOrDefault();
            if (null == robot)
                return new HttpNotFoundResult();
            //var item = robot.Mappings.Where(m => m.Id == id).SingleOrDefault();
            //if (null == item)
            //    return new HttpNotFoundResult();
            Mapping item = null;

            ViewBag.RobotId = robotId;
            ViewBag.ServerId = serverId;
            ViewBag.MappingId = id;

            if (Request.IsAjaxRequest())
                return PartialView(item);
            return View(item);
        }

        //
        // POST: /Mapping/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, int robotId, int serverId, string name)
        {
            try
            {
                if (string.IsNullOrEmpty(name))
                    throw new ArgumentNullException("name");
                var server = ParagonRCC_MVC3.Models.Server.Servers.Where(s => s.Id == serverId).SingleOrDefault();
                if (null == server)
                    return new HttpNotFoundResult();
                var robot = server.Robots.Where(r => r.Id == robotId).SingleOrDefault();
                if (null == robot)
                    return new HttpNotFoundResult();
                //var item = robot.Mappings.Where(m => m.Id == id).SingleOrDefault();
                //if (null == item)
                //    return new HttpNotFoundResult();

                //item.Name = name;
                // save
                if (Request.IsAjaxRequest())
                    return new HttpStatusCodeResult(200);
                return RedirectToAction("Index");
            }
            catch
            {
                if (Request.IsAjaxRequest())
                    return new HttpStatusCodeResult(400, "name is required and must not be empty");
                return View();
            }
        }

        //
        // GET: /Mapping/Delete/5
 
        public ActionResult Delete(int id, int robotId, int serverId)
        {
            var server = ParagonRCC_MVC3.Models.Server.Servers.Where(s => s.Id == serverId).SingleOrDefault();
            if (null == server)
                return new HttpNotFoundResult();
            var robot = server.Robots.Where(r => r.Id == robotId).SingleOrDefault();
            if (null == robot)
                return new HttpNotFoundResult();
            //var item = robot.Mappings.Where(m => m.Id == id).SingleOrDefault();
            //if (null == item)
            //    return new HttpNotFoundResult();
            Mapping item = null;

            ViewBag.RobotId = robotId;
            ViewBag.ServerId = serverId;
            ViewBag.MappingId = id;

            if (Request.IsAjaxRequest())
                return PartialView(item);
            return View(item);
        }

        //
        // POST: /Mapping/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirm(int id, int robotId, int serverId)
        {
            try
            {
                var server = ParagonRCC_MVC3.Models.Server.Servers.Where(s => s.Id == serverId).SingleOrDefault();
                if (null == server)
                    return new HttpNotFoundResult();
                var robot = server.Robots.Where(r => r.Id == robotId).SingleOrDefault();
                if (null == robot)
                    return new HttpNotFoundResult();
                //var item = robot.Mappings.Where(m => m.Id == id).SingleOrDefault();
                //if (null == item)
                //    return new HttpNotFoundResult();

                //robot.Mappings.Remove(item);
                // save
                if (Request.IsAjaxRequest())
                    return new HttpStatusCodeResult(200);
                return RedirectToAction("Index");
            }
            catch
            {
                if (Request.IsAjaxRequest())
                    return new HttpStatusCodeResult(400);
                return View();
            }
        }

        [HttpPost]
        public ActionResult Copy(string name, int robotId, int serverId, int id)
        {
            try
            {
                if (string.IsNullOrEmpty(name))
                    throw new ArgumentNullException("newName");
                var server = ParagonRCC_MVC3.Models.Server.Servers.Where(s => s.Id == serverId).SingleOrDefault();
                if (null == server)
                    return new HttpNotFoundResult();
                var robot = server.Robots.Where(r => r.Id == robotId).SingleOrDefault();
                if (null == robot)
                    return new HttpNotFoundResult();
                //var item = robot.Mappings.Where(m => m.Id == id).SingleOrDefault();
                //if (null == item)
                //    return new HttpNotFoundResult();
                //int newId = robot.Mappings.Max(m => m.Id) + 1;
                //var mapping = new Mapping() { Id = newId, Name = name, Order = newId, Transforms = new List<Transform>(), Conditions = new List<Condition>() };
                //foreach (var c in item.Conditions)
                //    mapping.Conditions.Add(
                //        new Condition( 
                //            ((mapping.Conditions.Count > 0) ? (mapping.Conditions.Max(cc => cc.Id) + 1) : 1), c));
                //foreach (var t in item.Transforms)
                //    mapping.Transforms.Add(

ParagonRCC-MVC3/ParagonRCC-MVC3/Controllers/RobotSettingController.cs
//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Web;
//using System.Web.Mvc;

//namespace ParagonRCC_MVC3.Controllers
//{
//    public class RobotSettingController : Controller
//    {
//        //
//        // GET: /RobotSetting/

//        public ActionResult Index(int serverId, int robotId)
//        {
//            var server = ParagonRCC_MVC3.Models.Server.Servers.Where(s => s.Id == serverId).SingleOrDefault();
//            if (null == server)
//                return new HttpNotFoundResult();
//            var robot = server.Robots.Where(r => r.Id == robotId).SingleOrDefault();
//            if (null == robot)
//                return new HttpNotFoundResult();
//            var list = robot.Settings.GroupBy(s => s.Group);
//            //var l2 = robot.Settings.Select(s => s.Group).Distinct();
//            ViewData["robotId"] = robotId;
//            ViewData["serverId"] = serverId;
//            //ControllerContext.ParentActionViewContext.GetType();
            
//            if (Request.IsAjaxRequest())
//                return PartialView(list);
//            return View(list);
//        }

//        public ActionResult Group(int serverId, int robotId, string group)
//        {
//            var server = ParagonRCC_MVC3.Models.Server.Servers.Where(s => s.Id == serverId).SingleOrDefault();
//            if (null == server)
//                return new HttpNotFoundResult();
//            var robot = server.Robots.Where(r => r.Id == robotId).SingleOrDefault();
//            if (null == robot)
//                return new HttpNotFoundResult();
//            var list = robot.Settings.Where(s => s.Group == group);
//            //var l2 = robot.Settings.Select(s => s.Group).Distinct();
//            ViewData["robotId"] = robotId;
//            ViewData["serverId"] = serverId;
//            ViewData["groupName"] = group;
//            //ControllerContext.ParentActionViewContext.GetType();

//            if (Request.IsAjaxRequest())
//                return PartialView(list);
//            return View(list);
//        }

//        //
//        // GET: /RobotSetting/Details/5

//        public ActionResult Details(int serverId, int id, int robotId)
//        {
//            return View();
//        }

//        //
//        // GET: /RobotSetting/Create

//        public ActionResult Create(int serverId, int robotId)
//        {
//            return View();
//        } 

//        //
//        // POST: /RobotSetting/Create

//        [HttpPost]
//        public ActionResult Create(int serverId, int robotId, FormCollection collection)
//        {
//            try
//            {
//                // TODO: Add insert logic here

//                return RedirectToAction("Index");
//            }
//            catch
//            {
//                return View();
//            }
//        }
        
//        //
//        // GET: /RobotSetting/Edit/5

//        public ActionResult Edit(int serverId, int robotId, int id)
//        {
//            return View();
//        }

//        //
//        // POST: /RobotSetting/Edit/5

//        [HttpPost]
//        public ActionResult Edit(int serverId, int robotId, int id, string value)
//        {
//            try
//            {
//                // TODO: Add update logic here
//                var server = ParagonRCC_MVC3.Models.Server.Servers.Where(s => s.Id == serverId).SingleOrDefault();
//                if (null == server)
//                    return new HttpNotFoundResult();
//                var robot = server.Robots.Where(r => r.Id == robotId).SingleOrDefault();
//                if (null == robot)
//                    return new HttpNotFoundResult();
//                var item = robot.Settings.Where(setting => setting.Id == id).SingleOrDefault();
//                if (null == item)
//                    return new HttpNotFoundResult();
//                item.Value = value;
 
//                return new HttpStatusCodeResult(200, "OK");
//            }
//            catch (Exception ex)
//            {
//                throw new HttpException("Exception while updating Robot Setting", ex);
//            }
//        }

//        //
//        // GET: /RobotSetting/Delete/5

//        public ActionResult Delete(int serverId, int robotId, int id)
//        {
//            return View();
//        }

//        //
//        // POST: /RobotSetting/Delete/5

//        [HttpPost]
//        public ActionResult Delete(int serverId, int robotId, int id, FormCollection collection)
//        {
//            try
//            {
//                // TODO: Add delete logic here
 
//                return RedirectToAction("Index");
//            }
//            catch
//            {
//                return View();
//            }
//        }
//    }
//}

ParagonRCC-MVC3/ParagonRCC-MVC3/Views/RobotSetting/Group.cshtml
@model IEnumerable<Paragon.RobotServices.Model.ModuleSetting>

@{
    ViewBag.Title = "Group";
}

@{var href = string.Format("S{0}-R{1}-G{2}", ViewData["serverId"], ViewData["robotId"], ViewData["groupName"]); }
<div class="settingGroup" id="@href">
@if (Model.Count() > 1)
{
<table width="100%" border="1">
    @foreach (var item in Model)
    {
        //var settingType = ParagonRCC_MVC3.Models.SettingType.Types.Where(s => s.Id == item.SettingTypeId).Select(s => s.Type);
        <tr class="settingItem">
            <th>@item.Label</th>
            <td>
                @{
            switch (item.SettingTypeId)
            {
                case 1:
                    if (item.Value.AsBool())
                    {
                            <text>
                                <input type="checkbox" checked="checked" name="@item.Name" />
                            </text>
                    }
                    else
                    {
                            <text>
                                <input type="checkbox" name="@item.Name" />
                            </text>
                    }
                    break;
                case 2:
                case 3:
                            <text>
                            @Html.TextBox(@item.Name, @item.Value)
                            </text>
                       break;
                case 4:
                            <text>
                            @Html.TextArea(@item.Name, @item.Value)
                            </text>
                       break;
                case 5:
                            <text>
                                @Html.DropDownList(@item.Name, new SelectList(@item.Values, "Value", "Key", @item.Value))
                            </text>
                       break;
                case 6:
                   var dict = item.Value.Split(";".ToCharArray())
                       .ToDictionary(m => m.Split("=".ToCharArray())[0], m => m.Split("=".ToCharArray())[1]);
                            <text>
                            <table> <!-- name="@item.Name"> -->
                              <thead>
                                <tr>
                                    <th colspan="2"></th>
                                    <th>Actions
                                        <span class="ui-icon ui-icon-plusthick" title="Create"></span>
                                        <!-- <span class="ui-icon ui-icon-refresh" title="Refresh"></span> -->
                                    </th>
                                </tr>
                              </thead>
                              <tbody>
                                @foreach (var kvp in dict)
                                {
                                    <tr>
                                    <th><input type="text" name="key" value="@kvp.Key" readonly="readonly" /></th>
                                    <td><input type="text" name="name" value="@kvp.Value" /></td>
                                    <td>
                                        <span class="ui-icon ui-icon-trash" title="Delete"></span>
                                        <span class="ui-icon ui-icon-copy" title="Copy"></span>
                                    </td>
                                    </tr>
                                }
                              </tbody>
                            </table>
                            </text>
                                break;
                       default:
                            <text>
                            @Html.TextBox(@item.Name, @item.Value)
                            </text>
                       break;
            }
        }
            </td>
            <td class="ui-helper-hidden">
                <span class="settingUrl">/RobotSetting/Edit/@item.Id?serverId=@ViewData["serverId"]&robotId=@ViewData["robotId"]</span>
                <span class="settingType">@item.SettingTypeId</span>
            </td>
        </tr>
    }
</table>
}
else if (Model.Count() == 1)
{
    @* e.g., for a Mappings setting group *@
    foreach (var item in Model) @* will only happen once, but still ... *@
    {
        var mappings = Paragon.RobotServices.Model.Mapping.FromXml(item.Value);
        //var settingType = ParagonRCC_MVC3.Models.SettingType.Types.Where(s => s.Id == item.SettingTypeId).Select(s => s.Type);
        <div class="mappings">
        Html.Partial("Mappings", mappings);
        <div class="ui-helper-hidden">
            <span class="settingUrl">/RobotSetting/Edit/@item.Id?serverId=@ViewData["serverId"]&robotId=@ViewData["robotId"]</span>
            <span class="settingType">@item.SettingTypeId</span>
        </div>
        </div>
    }
}

</div>

ParagonRCC-MVC3/ParagonRCC-MVC3/Views/RobotSetting/Index.cshtml
@model IEnumerable<IGrouping<string, ParagonRCC_MVC3.Models.Setting>>

@{
    ViewBag.Title = "Index";
}

<div class="settingForm">
<ul>
    @foreach (var item in Model)
    {
        @*
        var href = string.Format("#S{0}-R{1}-G{2}", ViewData["serverId"], ViewData["robotId"], item.Key);
        <li><a href="@href"><span>@item.Key</span></a></li>
        *@
        <li><a href='@Url.Action("Group", new { serverId =  ViewData["serverId"], robotId = ViewData["robotId"], group = item.Key})'>@item.Key</a></li>
    }
    <li><a href="#Save"><span class="ui-icon ui-icon-disk" title="Save">@Url.Action("Settings", "Robot", new { id = ViewData["robotId"], serverId = ViewData["serverId"] })</span></a></li>

</ul>
@*
    @foreach (var item in Model)
    {
        ViewData["GroupName"] = item.Key;
        @Html.Partial("Group", item)
    }
*@
</div>
<script type="text/javascript">
    $(function () {
        $(".settingForm:visible").tabs({
            select: function (event, ui) {
                if ($(ui.tab).attr('href') == '#Save') {
                    var href = $(ui.tab).find("span .ui-icon-disk").text();
                    saveSettings(href, $(".settingForm:visible div"));
                    return false;
                }
            },
            cache: false,
            ajaxOptions: { cache: false }
        });
        $(".settingForm:visible .sortable").sortable({
            revert: true,
            scroll: true,
            opacity: 0.7,
            axis: 'y',
            containment: 'parent',
            cursor: 'move'
        });
    });
</script>

ParagonRCC-MVC3/ParagonRCC-MVC3/Views/RobotSetting/Mappings.cshtml
@model IEnumerable<ParagonRCC_MVC3.Models.Mapping>

@{
    ViewBag.Title = "Mappings";
}

<div class="mappingTabs">
    <ul>
    @foreach (var item in Model)
    {
        <li class="sortable" title="drag to sort"><a href="@Url.Action("Details", "Mapping", 
                new { id = @item.Id, robotId = ViewData["robotId"], serverId = ViewData["serverId"] })">
            <span>@item.Name</span>
            <span class="ui-icon ui-icon-trash" title="Delete">@Url.Action("Delete", "Mapping", 
                new { id = @item.Id, robotId = ViewData["robotId"], serverId = ViewData["serverId"] })</span>
            <span class="ui-icon ui-icon-copy" title="Copy">@Url.Action("Copy", "Mapping", 
                new { id = @item.Id, robotId = ViewData["robotId"], serverId = ViewData["serverId"] })</span>
            <span class="ui-icon ui-icon-pencil" title="Edit">@Url.Action("Edit", "Mapping", 
                new { id = @item.Id, robotId = ViewData["robotId"], serverId = ViewData["serverId"], name="" })</span>
        </li>
    }
    <li><a href="#newTab"><span class="ui-icon ui-icon-plusthick" title="Create"></span></a></li>
    </ul>
</div>