ParagonRCC-MVC3/ParagonRCC-MVC3/Models/Audit.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ParagonRCC_MVC3.Models
{
    public class Audit
    {
        public int Id { get; set; }
        public bool Enabled { get; set; }
        public Login Login { get; set; }
        public string AuditTableName { get; set; }
        public string IdFieldName { get; set; }
        public string SuccessIndicator { get; set; }
        public string ErrorIndicator { get; set; }

        public Audit() 
        {
            Enabled = false;
            Login = new Login();
        }

        public Audit(AuditSaveSettings save)
        {
            this.Id = save.Id;
            this.Enabled = save.Enabled;
            this.Login = new Login(save.AsConnString());
            this.AuditTableName = save.AuditTableName;
            this.IdFieldName = save.IdFieldName;
            this.SuccessIndicator = save.SuccessIndicator;
            this.ErrorIndicator = save.ErrorIndicator;
        }
    }

    public class AuditSaveSettings
    {
        public int Id { get; set;}
        public bool Enabled {get; set;}
        public string Provider {get; set;}
        public string Server {get; set;}
        public string Database {get; set;}
        public string UserId {get; set;}
        public string Password {get; set;}
        public string AuditTableName { get; set; }
        public string IdFieldName { get; set; }
        public string SuccessIndicator { get; set; }
        public string ErrorIndicator { get; set; }

        public string AsConnString()
        {
            return string.Format("provider={0}&server={1}&database={2}&userid={3}&password={4}",
                Provider, Server, Database, UserId, Password);
        }
    }
}

ParagonRCC-MVC3/ParagonRCC-MVC3/Models/Login.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Text;

namespace ParagonRCC_MVC3.Models
{
    public class Login
    {
        public string Provider;
        public string Server;
        public string Database;
        public string UserId;
        public string Password;

        public Login() { }

        public Login(string details)
        {
            string[] kvpItems = details.Split("&".ToCharArray());
            foreach (var item in kvpItems)
            {
                string[] kvp = item.Split("=".ToCharArray(), 2);
                switch (kvp[0].ToLower())
                {
                    case "provider":
                        this.Provider = kvp[1];
                        break;
                    case "server":
                        this.Server = kvp[1];
                        break;
                    case "database":
                        this.Database = kvp[1];
                        break;
                    case "userid":
                        this.UserId = kvp[1];
                        break;
                    case "password":
                        this.Password = kvp[1];
                        //Decryptdata(kvp[1]);
                        break;
                }
            }
        }

        
    }
}

ParagonRCC-MVC3/ParagonRCC-MVC3/Models/Setting.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ParagonRCC_MVC3.Models
{
    public class Setting
    {
        public int Id;
        public string Name;
        public string Value;
        public string Type;
    }
}

ParagonRCC-MVC3/ParagonRCC-MVC3/Controllers/ConditionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ParagonRCC_MVC3.Models;

namespace ParagonRCC_MVC3.Controllers
{
    public class ConditionController : Controller
    {
        public static List<Conditional> Conditionals = new List<Conditional> 
                {
                new Conditional() { Id = 1, Name = "Equals"},
                new Conditional() { Id = 2, Name = "NotEquals"},
                new Conditional() { Id = 3, Name = "IsBlank"},
                new Conditional() { Id = 4, Name = "IsNotBlank"},
                new Conditional() { Id = 5, Name = "StartsWith"},
                new Conditional() { Id = 6, Name = "EndsWith"},
                new Conditional() { Id = 7, Name = "GreaterThan"},
                new Conditional() { Id = 8, Name = "GreaterThanOrEqual"},
                new Conditional() { Id = 9, Name = "LessThan"},
                new Conditional() { Id = 10, Name = "LessThanOrEqual"},
                new Conditional() { Id = 11, Name = "Contains"},
                new Conditional() { Id = 12, Name = "InList"},
                new Conditional() { Id = 13, Name = "NotInList"},
                new Conditional() { Id = 14, Name = "Like"},
                new Conditional() { Id = 15, Name = "NotLike" }
                };

            /* new SelectList(new[]
                {
                new { Id = 1, Name = "Equals"},
                new { Id = 2, Name = "NotEquals"},
                new { Id = 3, Name = "IsBlank"},
                new { Id = 4, Name = "IsNotBlank"},
                new { Id = 5, Name = "StartsWith"},
                new { Id = 6, Name = "EndsWith"},
                new { Id = 7, Name = "GreaterThan"},
                new { Id = 8, Name = "GreaterThanOrEqual"},
                new { Id = 9, Name = "LessThan"},
                new { Id = 10, Name = "LessThanOrEqual"},
                new { Id = 11, Name = "Contains"},
                new { Id = 12, Name = "InList"},
                new { Id = 13, Name = "NotInList"},
                new { Id = 14, Name = "Like"},
                new { Id = 15, Name = "NotLike" }
                }, "Id", "Name"); */

        public static List<Connector> Connectors = new List<Connector> {
                    new Connector() { Id = 1, Name = "And" },
                    new Connector() { Id = 2, Name = "Or" }
                };
                /* new SelectList(new[] 
                {
                    new { Id = 1, Name = "And" },
                    new { Id = 2, Name = "Or" }
                }, "Id", "Name"); */

        //
        // GET: /Condition/

        public ActionResult Index(int mappingId, int robotId, int serverId)
        {
            var server = ParagonRCC_MVC3.Models.Server.Servers.Where(s => s.Id == serverId).SingleOrDefault();
            if (null == server)
                return new HttpNotFoundResult();
            var robot = server.Robots.Where(r => r.Id == robotId).SingleOrDefault();
            if (null == robot)
                return new HttpNotFoundResult();
            //var mapping = robot.Mappings.Where(m => m.Id == mappingId).SingleOrDefault();
            //if (null == mapping)
            //    return new HttpNotFoundResult();
            //var list = mapping.Conditions.OrderBy(c => c.Order);
            object list = null;
            ViewBag.MappingId = mappingId;
            ViewBag.RobotId = robotId;
            ViewBag.ServerId = serverId;

            ViewBag.Connectors = ConditionController.Connectors;
            ViewBag.Conditionals = ConditionController.Conditionals;

            if (Request.IsAjaxRequest())
                return PartialView(list);
            return View(list);
        }

        //
        // GET: /Condition/Details/5

        public ActionResult Details(int id, int mappingId, int robotId, int serverId)
        {
            var server = ParagonRCC_MVC3.Models.Server.Servers.Where(s => s.Id == serverId).SingleOrDefault();
            if (null == server)
                return new HttpNotFoundResult();
            var robot = server.Robots.Where(r => r.Id == robotId).SingleOrDefault();
            if (null == robot)
                return new HttpNotFoundResult();
            //var mapping = robot.Mappings.Where(m => m.Id == mappingId).SingleOrDefault();
            //if (null == mapping)
            //    return new HttpNotFoundResult();
            //var item = mapping.Conditions.Where(c => c.Id == id).SingleOrDefault();
            //if (null == item)
            //    return new HttpNotFoundResult();
            object item = null;

            ViewBag.MappingId = mappingId;
            ViewBag.RobotId = robotId;
            ViewBag.ServerId = serverId;

            //ViewBag.ConnectorId = new SelectList(ConditionController.Connectors, "Id", "Name", item.ConnectorId);
            //ViewBag.ConditionalId = new SelectList(ConditionController.Conditionals, "Id", "Name", item.ConditionalId);

            if (Request.IsAjaxRequest())
                return PartialView("~/Views/Shared/Condition.cshtml",item);
            return View("~/Views/Shared/Condition.cshtml", item);
        }

        //
        // GET: /Condition/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Condition/Create

        [HttpPost]
        public ActionResult Create(int mappingId, int robotId, int serverId) //, int conditionalId, int connectorId, string operand1, string operand2)
        {
            try
            {
                var server = ParagonRCC_MVC3.Models.Server.Servers.Where(s => s.Id == serverId).SingleOrDefault();
                if (null == server)
                    return new HttpNotFoundResult();
                var robot = server.Robots.Where(r => r.Id == robotId).SingleOrDefault();
                if (null == robot)
                    return new HttpNotFoundResult();
                //var mapping = robot.Mappings.Where(m => m.Id == mappingId).SingleOrDefault();
                //if (null == mapping)
                //    return new HttpNotFoundResult();
                //var newId = mapping.Conditions.Max(t => t.Id) + 1;
                //var item = new Condition() { Id = newId, Order = newId };
                //mapping.Conditions.Add(item);
                Condition item = null;

                ViewBag.MappingId = mappingId;
                ViewBag.RobotId = robotId;
                ViewBag.ServerId = serverId;

                ViewBag.Connectors = ConditionController.Connectors;
                ViewBag.Conditionals = ConditionController.Conditionals;

                return RedirectToAction("Details", new { id = item.Id, mappingId = mappingId, robotId = robotId, serverId = serverId });
            }
            catch
            {
                return View();
            }
        }
        
        //
        // GET: /Condition/Edit/5
 
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Condition/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, int mappingId, int robotId, int serverId, int conditionalId, int connectorId, string operand1, string operand2)
        {
            try
            {
                var server = ParagonRCC_MVC3.Models.Server.Servers.Where(s => s.Id == serverId).SingleOrDefault();
                if (null == server)
                    return new HttpNotFoundResult();
                var robot = server.Robots.Where(r => r.Id == robotId).SingleOrDefault();
                if (null == robot)
                    return new HttpNotFoundResult();
                //var mapping = robot.Mappings.Where(m => m.Id == mappingId).SingleOrDefault();
                //if (null == mapping)
                //    return new HttpNotFoundResult();
                //var item = mapping.Conditions.Where(c => c.Id == id).SingleOrDefault();
                //if (null == item)
                //    return new HttpNotFoundResult();
                //item.ConditionalId = conditionalId;
                //item.ConnectorId = connectorId;
                //item.Operand1 = operand1;
                //item.Operand2 = operand2;
                Condition item = null;

                ViewBag.MappingId = mappingId;
                ViewBag.RobotId = robotId;
                ViewBag.ServerId = serverId;

                ViewBag.Connectors = ConditionController.Connectors;
                ViewBag.Conditionals = ConditionController.Conditionals;

                return RedirectToAction("Details", new { id = item.Id, mappingId = mappingId, robotId = robotId, serverId = serverId });
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Condition/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Condition/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, int mappingId, int robotId, int serverId)
        {
            try
            {
                var server = ParagonRCC_MVC3.Models.Server.Servers.Where(s => s.Id == serverId).SingleOrDefault();
                if (null == server)
                    return new HttpNotFoundResult();
                var robot = server.Robots.Where(r => r.Id == robotId).SingleOrDefault();
                if (null == robot)
                    return new HttpNotFoundResult();
                //var mapping = robot.Mappings.Where(m => m.Id == mappingId).SingleOrDefault();
                //if (null == mapping)
                //    return new HttpNotFoundResult();
                //var item = mapping.Conditions.Where(c => c.Id == id).SingleOrDefault();
                //if (null == item)
                //    return new HttpNotFoundResult();
                //mapping.Conditions.Remove(item);

                ViewBag.MappingId = mappingId;

ParagonRCC-MVC3/ParagonRCC-MVC3/Controllers/LookupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ParagonRCC_MVC3.Controllers
{
    public class LookupController : Controller
    {
        //
        // GET: /Lookup/

        public ActionResult Index(int robotId, int serverId)
        {
            var server = ParagonRCC_MVC3.Models.Server.Servers.Where(s => s.Id == serverId).SingleOrDefault();
            if (null == server)
                return new HttpNotFoundResult();
            var robot = server.Robots.Where(r => r.Id == robotId).SingleOrDefault();
            if (null == robot)
                return new HttpNotFoundResult();
            
            ViewBag.RobotId = robotId;
            ViewBag.ServerId = serverId;

            if (Request.IsAjaxRequest())
                return PartialView(robot.Lookup);
            return View(robot.Lookup);
        }

        //
        // GET: /Lookup/Details/5

        public ActionResult Details(int robotId, int serverId)
        {
            var server = ParagonRCC_MVC3.Models.Server.Servers.Where(s => s.Id == serverId).SingleOrDefault();
            if (null == server)
                return new HttpNotFoundResult();
            var robot = server.Robots.Where(r => r.Id == robotId).SingleOrDefault();
            if (null == robot)
                return new HttpNotFoundResult();

            ViewBag.RobotId = robotId;
            ViewBag.ServerId = serverId;

            if (Request.IsAjaxRequest())
                return PartialView(robot.Lookup);
            return View(robot.Lookup);
        }

        //
        // GET: /Lookup/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Lookup/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        
        //
        // GET: /Lookup/Edit/5
 
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Lookup/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Lookup/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Lookup/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ParagonRCC-MVC3/ParagonRCC-MVC3/Views/Robot/Audit.cshtml
@* @model ParagonRCC_MVC3.Models.Audit *@
@model Paragon.RobotServices.Model.Audit

@{
    ViewBag.Title = "Audit";
}

@helper CheckBox(string name, bool arg) {
    if (arg) {
        <input type="checkbox" name="@name" checked="checked" />
    }
    else {
        <input type="checkbox" name="@name" />
    }
}

<div class="auditForm">
<table>
    <tr class="ui-helper-hidden">
        <td><input type="hidden" name="id"value="@Model.Id" /></td>
    </tr>
    <tr>
        <td><span class="display-label">Enabled</span></td>
        <td><span class="display-field">@CheckBox("enabled", Model.Enabled)</span></td>
    </tr>
    <tr>
        <td><span class="display-label">Login</span></td>
        <td><span class="display-field">@Html.Partial("Login", Model.Login)</span></td>
    </tr>
    <tr>
        <td><span class="display-label">Audit Table Name</span></td>
        <td><span class="display-field">@Html.TextBox("auditTableName", Model.AuditTableName)</span></td>
    </tr>
    <tr>
        <td><span class="display-label">Id Field Name</span></td>
        <td><span class="display-field">@Html.TextBox("idFieldName", Model.IdFieldName)</span></td>
    </tr>
    <tr>
        <td><span class="display-label">Success Indicator</span></td>
        <td><span class="display-field">@Html.TextBox("successIndicator", Model.SuccessIndicator)</span></td>
    </tr>
    <tr>
        <td><span class="display-label">Error Indicator</span></td>
        <td><span class="display-field">@Html.TextBox("errorIndicator", Model.ErrorIndicator)</span></td>
    </tr>
</table>
</div>

ParagonRCC-MVC3/ParagonRCC-MVC3/Views/Robot/Conditions.cshtml
@model IEnumerable<Paragon.RobotServices.Model.Condition>

@{
    ViewBag.Title = "Conditions";
}

<div class="conditions">
<div class="conditionsHeader">
<span>Conditions</span>
</div>
<table>
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Conditional</th>
            <th>Value</th>
            <th>Connector</th>
            <th><span class="ui-icon ui-icon-plusthick" title="Create"></span></th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        @Html.Partial("~/Views/Shared/Condition.cshtml", item)
    }   
    </tbody>
</table>
<script type="text/javascript">
    $(function () {
        $(".conditions tbody").sortable({
            /* update: sortTable, */
            revert: true,
            scroll: true,
            opacity: 0.7,
            axis: 'y',
            containment: 'parent',
            cursor: 'move'
        });
    });
</script>
</div>

ParagonRCC-MVC3/ParagonRCC-MVC3/Views/Robot/Details.cshtml
@using ParagonRCC_MVC3
@model Paragon.RobotServices.Model.Robot

@*
<fieldset>
    <legend>Robot</legend>
    @Html.TextBoxFor(r => r.Name)
    @Html.TextBoxFor(r => r.Status)
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>
*@

<div class="robotForm">

<table width="100%" border="0">
<tr>
<td width="20%">
    @* Html.ActionImage("~/Content/images/icon/clock.png", "Schedule", new { id = @Model.Id, serverID = "" }, null, null, new { alt = "Toggle Schedule Mode" }, null) *@
    @* Html.ActionImage("Schedule", new { id = @Model.Id }, "~/Content/images/icon/clock.png", "Toggle Scheduled Mode") *@
    @* Html.ActionImage("~/Content/images/icon/button_play_green.png", "Start", new { id = @Model.Id, serverID = "" }, null, null, new { alt = "Start Robot" }, null) *@
    @* Html.ActionImage("Start", new { id = @Model.Id }, "~/Content/images/icon/button_play_green.png", "Start Robot") *@
    @* Html.ActionImage("~/Content/images/icon/button_grey_stop.png", "Start", new { id = @Model.Id, serverID = "" }, null, null, new { alt = "Stop Robot" }, null) *@
    @* Html.ActionImage("c", new { id = @Model.Id }, "~/Content/images/icon/button_grey_stop.png", "Stop Robot") *@

    @if (Model.IsScheduled == false)
    {
        <a class="nodeLink" href='@Url.Action("ScheduledToggle", new { id = Model.Id, serverId = ViewData["serverId"], isSchedule = true })' title="Schedule - @Model.Name">
            <img class="moduleIcon" alt="Toggle Scheduled Mode" src="@Url.Content("~/Content/images/icon/clock.png")" />
        </a>
    }
    else
    {
        <a class="nodeLink" href='@Url.Action("ScheduledToggle", new { id = Model.Id, serverId = ViewData["serverId"], isSchedule = false })' title="Schedule - @Model.Name">
            <img class="moduleIconActive" alt="Toggle Scheduled Mode" src="@Url.Content("~/Content/images/icon/clock.png")" />
        </a>
    } 
    @if (Model.IsScheduled == false)
    {
        <a class="nodeLink" href='@Url.Action("Start", new { id = Model.Id, serverId = ViewData["serverId"] })' title="Start - @Model.Name">
            <img class="moduleIcon" alt="Start" src="@Url.Content("~/Content/images/icon/button_grey_play.png")" />
        </a>
    }
    <a class="nodeLink" href='@Url.Action("Stop", new { id = Model.Id, serverId = ViewData["serverId"] })' title="Stop - @Model.Name">
        <img class="moduleIcon" alt="Stop" src="@Url.Content("~/Content/images/icon/button_grey_stop.png")" />
    </a>

    @* 
        <a class="nodeLink" href="/Robot/ScheduledToggle/@Model.Id?serverId=@ViewData["serverId"]" title="Toggle Scheduled Mode - @Model.Name">
        <img class="moduleIcon" alt="Toggle Scheduled Mode" src="@Url.Content("~/Content/images/icon/clock.png")" />
    </a>
<a class="nodeLink" href="/Robot/Start/@Model.Id?serverId=@ViewData["serverId"]" title="Start - @Model.Name ">
        <img class="moduleIcon" alt="Start" src="@Url.Content("~/Content/images/icon/button_grey_play.png")" />
    </a> 
    <a class="nodeLink" href="/Robot/Stop/@Model.Id?serverId=@ViewData["serverId"]" title="Stop - @Model.Name ">
        <img class="moduleIcon" alt="Stop" src="@Url.Content("~/Content/images/icon/button_grey_stop.png")" />
    </a>*@
</td>
<td width="80%" align="center">
<div class="robotTitle"><p>@Model.Name</p></div>
</td>
</tr>
</table>
<div class="robotTabs">
    <ul>
        @* <li><a href="#tabs-1">Logging</a> *@
        @*<li>@Html.ActionLink("Logging", "Logging", new { id = @Model.Id, serverId = ViewData["serverId"], critical = "critical", error = "error", warning = "warning", normal = "normal", debug = "debug" })</li> 
        <li>@Html.ActionLink("Scheduling", "Schedules", new { id = @Model.Id, serverId = ViewData["serverId"] })</li>
        <li>@Html.ActionLink("Notification", "Notification", new { id = @Model.Id, serverId = ViewData["serverId"] })</li>
        <li>@Html.ActionLink("Image Normalization", "Normalization", new { id = @Model.Id, serverId = ViewData["serverId"] })</li>
        <li>@Html.ActionLink("Test Login", "TestLogin", new { id = @Model.Id, serverId = ViewData["serverId"] })</li>
        <li>@Html.ActionLink("Settings", "Settings", new { id = @Model.Id, serverId = ViewData["serverId"] })</li>
        <li>@Html.ActionLink("Mappings", "Mappings", new { id = @Model.Id, serverId = ViewData["serverId"] })</li>
        <li>@Html.ActionLink("Lookups", "Index", "Lookup", new { robotId = @Model.Id, serverId = ViewData["serverId"] }, null)</li>*@
        <li title="Logging: Displays the latest robot logs sorted by categories">@Html.ActionSpan("Logging", "Robot", new { id = @Model.Id, serverId = ViewData["serverId"], critical = "critical", error = "error", warning = "warning", normal = "normal", debug = "debug" }, "Log", null, null)
        </li>       
        <li title="Scheduling: Displays different scheduling options available in the robot">@Html.ActionSpan("Scheduling", "Robot", new { id = @Model.Id, serverId = ViewData["serverId"] }, "Schedule", null, null)
        </li>        
        <li title="Notification: Displays Event/Notifications that can be set in the robot">@Html.ActionSpan("Notification", "Robot", new { id = @Model.Id, serverId = ViewData["serverId"] }, "Notify", null, null)
        </li>
        <li title="Audit: Displays auditing configuration for the robot">@Html.ActionSpan("Audit", "Robot", new { id = @Model.Id, serverId = ViewData["serverId"] }, "Audit", null, null)
        </li>       
        <li title="Input: Displays input configuration options">@Html.ActionSpan("Input", "Robot", new { id = @Model.Id, serverId = ViewData["serverId"] }, "Input", null, null)
        </li>
        @if (Model.Liscence != null && Model.Liscence.CanNormalize && (!Model.Liscence.IsLiscenceExpired))
        {
            if (Model.Liscence.ExpirationDate >= DateTime.Now)
            {
                <li title="Normalization: Displays Image enhancements options available"> @Html.ActionSpan("Normalization", "Robot", new { id = @Model.Id, serverId = ViewData["serverId"] }, "Normalize Image", null, null)
                </li>
            }
        }
        
        @if (Model.Liscence != null && Model.Liscence.CanLookup && (!Model.Liscence.IsLiscenceExpired))
        {
            if (Model.Liscence.ExpirationDate >= DateTime.Now)
            {
                <li title="Lookups: Displays settings used to perform database lookups">@Html.ActionSpan("Lookup", "Robot", new { id = @Model.Id, serverId = ViewData["serverId"] }, "Data Lookup", null, null)
                </li>
            }
        }
        
        @if (Model.Liscence != null && Model.Liscence.CanMap && (!Model.Liscence.IsLiscenceExpired))
        {
            if (Model.Liscence.ExpirationDate >= DateTime.Now)
            {
                <li title="Data Mappings: Displays conditional settings that are translated by Robot's Transformation engine for data manupulation">@Html.ActionSpan("Mappings", "Robot", new { id = @Model.Id, serverId = ViewData["serverId"] }, "Data Mapping", null, null)
                </li>
            }
        }
        <li title="Output: Displays output configuration options">@Html.ActionSpan("Output", "Robot", new { id = @Model.Id, serverId = ViewData["serverId"] }, "Output", null, null)
        </li>
        <li title="Save: Saves robot options"><a href="#saveRobot"><span class="ui-icon ui-icon-disk">@Url.Action("Save", new { id = @Model.Id, serverId = ViewData["serverId"] })</span></a>
        </li>
        <div style="width:25%; float:right">
        <a class="displayChart" href="@Url.Action("DisplayChart", new { id = Model.Id, serverId = ViewData["serverId"], robotName = @Model.Name })" >Show Chart</a>
        <br />
        <a style="float:right;" href="@Url.Action("ExportImport", new { id = Model.Id, serverId = ViewData["serverId"], inputModuleId = @Model.InputModuleId, outputModuleId = @Model.OutputModuleId })" >Export/Import Settings</a>
        </div>
    </ul>
</div>
<div class="robotStatus">
    <p>@Model.Name Status:  @Model.Status.ToString()</p>
    <p>Items processed successfully: @Model.SuccessCount</p>
    <p style="text-align:right;color:Red">@if(Model.Liscence != null){ <b>@Model.Liscence.Message</b> } </p>
</div>
</div>
<script type="text/javascript">
    $(function () {
        
        makeRobotTabs();
    });

//    $(document).ready(function () {
//        alert(document.getElementById("displayMessage").value);
//    });
//    $(document).ready(function () {
//        var url = '@Url.Action("SaveLicense", "Robot")';
//        var data = {};
//        $.ajax({
//            type: "Get",
//            url: url,
//            data: { serverId: serverId, id: id, licenseKey: licenseKey },
//            cache: false,
//            dataType: 'html',
//            success: function (result) {
//                alert("Saved");
//            }
//        });
//    });
</script>

ParagonRCC-MVC3/ParagonRCC-MVC3/Views/Robot/Export.cshtml
@{
    ViewBag.Title = "Export";
}
<script type="text/javascript">
    window.onbeforeunload = function (e) {
        alert("dsfsadfsdf");
    }
</script>
<h2>Export</h2>