ParagonRCC-MVC3/ParagonRCC-MVC3/Models/Condition.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Xml.Linq;
using System.Web;

namespace ParagonRCC_MVC3.Models
{
    public class Condition
    {
        public int Id;
        public string Operand1;
        public string Operand2;
        public int ConnectorId;// {get; set; }
        public int ConditionalId;// {get; set; }
        public int Order;

        public Condition() { ConditionalId = 1; ConnectorId = 1; }

        public Condition(int newId, Condition c)
        {
            this.Id = newId;
            this.Operand1 = c.Operand1;
            this.Operand2 = c.Operand2;
            this.ConditionalId = c.ConditionalId;
            this.ConnectorId = c.ConnectorId;
            this.Order = newId;
        }

        public Condition(XElement el)
        {
            if (el.Attribute("id") != null)
                int.TryParse(el.Attribute("id").Value, out this.Id);
            else
                throw new ArgumentException(string.Format("element {0} does not have an 'id' attribute, or the attribute is not a number.", el.ToString()));
            if (el.Attribute("order") != null)
                int.TryParse(el.Attribute("order").Value, out this.Order);
            else
                throw new ArgumentException(string.Format("element {0} does not have an 'order' attribute, or the attribute is not a number.", el.ToString()));
            if (el.Attribute("op1") != null)
                this.Operand1 = el.Attribute("op1").Value;
            else
                throw new ArgumentException(string.Format("element {0} does not have a 'op1' attribute.", el.ToString()));
            if (el.Attribute("op2") != null)
                this.Operand2 = el.Attribute("op2").Value;
            else
                throw new ArgumentException(string.Format("element {0} does not have a 'op2' attribute.", el.ToString()));
            if (el.Attribute("conditionalId") != null)
                int.TryParse(el.Attribute("conditionalId").Value, out this.ConditionalId);
            else
                throw new ArgumentException(string.Format("element {0} does not have an 'conditionalId' attribute, or the attribute is not a number.", el.ToString()));
            if (el.Attribute("connectorId") != null)
                int.TryParse(el.Attribute("connectorId").Value, out this.ConnectorId);
            else
                throw new ArgumentException(string.Format("element {0} does not have an 'connectorId' attribute, or the attribute is not a number.", el.ToString()));
        }

        public static List<Condition> FromElements(IEnumerable<XElement> els)
        {
            List<Condition> rv = new List<Condition>();
            rv.AddRange(els.Select(e => new Condition(e)));
            return rv;
        }
    }

    public class Connector
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public static readonly ReadOnlyCollection<Connector> Connectors = new ReadOnlyCollection<Connector>( new List<Connector>
            {
                new Connector() { Id = 1, Name = "And" },
                new Connector() { Id = 2, Name = "Or" }
            }
        );
    }

    public class Conditional
    {
        public int Id {get; set; }
        public string Name {get; set; }

        public static readonly ReadOnlyCollection<Conditional> Conditionals = new ReadOnlyCollection<Conditional>(new List<Conditional>
            {
                new Conditional() { Id = 1, Name = "Equals"},
                new Conditional() { Id = 2, Name = "NotEquals"},
                new Conditional() { Id = 3, Name = "IsBlank"},
                new Conditional() { Id = 4, Name = "IsNotBlank"},
                new Conditional() { Id = 5, Name = "StartsWith"},
                new Conditional() { Id = 6, Name = "EndsWith"},
                new Conditional() { Id = 7, Name = "GreaterThan"},
                new Conditional() { Id = 8, Name = "GreaterThanOrEqual"},
                new Conditional() { Id = 9, Name = "LessThan"},
                new Conditional() { Id = 10, Name = "LessThanOrEqual"},
                new Conditional() { Id = 11, Name = "Contains"},
                new Conditional() { Id = 12, Name = "InList"},
                new Conditional() { Id = 13, Name = "NotInList"},
                new Conditional() { Id = 14, Name = "Like"},
                new Conditional() { Id = 15, Name = "NotLike" }
            }
        );
    }
}

ParagonRCC-MVC3/ParagonRCC-MVC3/Models/Mapping.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Xml.Linq;

namespace ParagonRCC_MVC3.Models
{
    public class Mapping
    {
        public int Id;
        public string Name;
        public int Order;
        public List<Condition> Conditions = new List<Condition> { };
        public List<Transform> Transforms = new List<Transform> { };

        public Mapping() { }

        public Mapping(XElement el)
        {
            if (el.Attribute("id") != null)
                int.TryParse(el.Attribute("id").Value, out this.Id);
            else
                throw new ArgumentException(string.Format("element {0} does not have an 'id' attribute, or the attribute is not a number.", el.ToString()));
            if (el.Attribute("order") != null)
                int.TryParse(el.Attribute("order").Value, out this.Order);
            else
                throw new ArgumentException(string.Format("element {0} does not have an 'order' attribute, or the attribute is not a number.", el.ToString()));
            if (el.Attribute("name") != null)
                this.Name = el.Attribute("name").Value;
            else
                throw new ArgumentException(string.Format("element {0} does not have a 'name' attribute.", el.ToString()));
            Conditions.AddRange(Condition.FromElements(el.Elements("condition")));
            Transforms.AddRange(Transform.FromElements(el.Elements("transform")));
        }
        
        public static List<Mapping> FromXml(string xml)
        {
            if (string.IsNullOrEmpty(xml))
                xml = @"<mappings><mapping id='1' order='1' name='default'></mapping></mappings>";
            List<Mapping> rv = new List<Mapping>();
            try
            {
                XElement root = XElement.Parse(xml);
                rv.AddRange(root.Elements("mapping").Select(e => new Mapping(e)));
            }
            catch (Exception ex)
            {
                ex.ToString();
            }

            return rv;
        }
    }
}

ParagonRCC-MVC3/ParagonRCC-MVC3/Controllers/RobotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ParagonRCC_MVC3.Models;
using Paragon.RobotServices.Model;
using System.Web.UI.DataVisualization.Charting;
using System.Drawing;
using System.IO;
using System.Text;
using System.Reflection;
using System.Security.Cryptography;
using System.Xml;
using System.Configuration;

namespace ParagonRCC_MVC3.Controllers
{
    [System.Runtime.InteropServices.GuidAttribute("8091134D-5916-469F-B0E8-D47B1AF4E18A")]
    public class RobotController : Controller
    {
        private string filePath;
        private string FilePath
        {
            get
            {
                return Path.Combine(Server.MapPath("~/App_Data"), filePath);
            }
            set
            {
                filePath = value;
            }
        }

        string exportFilePath = ConfigurationManager.AppSettings["ExportXml"].ToString();
        string importFilePath = ConfigurationManager.AppSettings["ImportXml"].ToString();

        public string plainText;
        public string passPhrase = "Pas5pr@se";
        public string saltValue = "s@1tValue";
        public string hashAlgorithm = "MD5";
        public int passwordIterations = 2;
        public string initVector = "@1B2c3D4e5F6g7H8";
        public int keySize = 256;

        private object _value;

        protected ParagonRCC_MVC3.Models.Server _server;

        protected Robot FindRobot(int serverId, int robotId)
        {
            var server = ParagonRCC_MVC3.Models.Server.Servers.Where(s => s.Id == serverId).FirstOrDefault();
            if (server == null)
                throw new ServerNotFoundException(serverId);
            _server = server;
            var item = server.Robots.Where(r => r.Id == robotId).FirstOrDefault();
            ViewData["robotId"] = robotId;
            ViewData["serverId"] = serverId;
            if (item == null)
                throw new RobotNotFoundException(robotId);
            return item;
        }

        //
        // GET: /Robot/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Robot/Details/5

        public ActionResult Details(int id, int serverId)
        {
            try
            {
                Robot item = FindRobot(serverId, id);
                var server = ParagonRCC_MVC3.Models.Server.Servers.Where(s => s.Id == serverId).Single();
                var url = server.Uri.ToString();
                try
                {
                    var x = (System.Net.HttpWebRequest)System.Net.WebRequest.Create(url + string.Format("/robots/{0}", id));
                    x.CachePolicy = new System.Net.Cache.HttpRequestCachePolicy(System.Net.Cache.HttpRequestCacheLevel.NoCacheNoStore);
                    var resp = (System.Net.HttpWebResponse)x.GetResponse();
                    var xs = new System.Runtime.Serialization.DataContractSerializer(typeof(Paragon.RobotServices.Model.Robot));
                    //var ms = new System.IO.MemoryStream(r);
                    var bot = (Paragon.RobotServices.Model.Robot)xs.ReadObject(resp.GetResponseStream());
                    item = server.Robots[id] = bot;
                }
                catch (Exception ex)
                {
                    return new HttpStatusCodeResult(503, ex.ToString());
                }
                if (Request.IsAjaxRequest())
                    return PartialView(item);
                return View(item);
            }
            catch (ServerNotFoundException sEx)
            {
                return new HttpNotFoundResult(sEx.ToString());
            }
            catch (RobotNotFoundException rEx)
            {
                return new HttpNotFoundResult(rEx.ToString());
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        //
        // GET: /Robot/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Robot/Create

        [HttpPost]
        public ActionResult Create(Robot item)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Robot/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Robot/Edit/5

        [HttpPost]
        public ActionResult Edit(Robot item)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Robot/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Robot/Delete/5

        [HttpPost]
        public ActionResult Delete(Robot item)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Logging(int id, int serverId)
        {
            try
            {
                var item = FindRobot(serverId, id);
                IEnumerable<LogEntry> list = null;
                var url = _server.Uri.ToString();
                //var url = ParagonRCC_MVC3.Models.Server.Servers.Where(s => s.Id == serverId).Single().Uri.ToString();
                var x = (System.Net.HttpWebRequest)System.Net.WebRequest.Create(url + string.Format("/robots/{0}/logs", id));
                x.Method = "GET";
                x.CachePolicy = new System.Net.Cache.HttpRequestCachePolicy(System.Net.Cache.HttpRequestCacheLevel.NoCacheNoStore);
                System.Net.HttpWebResponse resp = null;
                try
                {
                    resp = (System.Net.HttpWebResponse)x.GetResponse();
                }
                catch (Exception ex)
                {
                    return new HttpStatusCodeResult(503, ex.ToString());
                }
                var dcs = new System.Runtime.Serialization.DataContractSerializer(typeof(List<Paragon.RobotServices.Model.LogEntry>));
                list = (List<Paragon.RobotServices.Model.LogEntry>)dcs.ReadObject(resp.GetResponseStream());

                bool asc = false;
                // severities logic
                if (null != Request)
                {
                    if (Request.Params["critical"] == null)
                        list = list.Where(l => l.Severity != LogSeverity.Critical);
                    if (Request.Params["error"] == null)
                        list = list.Where(l => l.Severity != LogSeverity.Error);
                    if (Request.Params["warning"] == null)
                        list = list.Where(l => l.Severity != LogSeverity.Warning);
                    if (Request.Params["normal"] == null)
                        list = list.Where(l => l.Severity != LogSeverity.Normal);
                    if (Request.Params["debug"] == null)
                        list = list.Where(l => l.Severity != LogSeverity.Debug);
                    if ((null != Request.Params["ascending"]) && (Request.Params["ascending"].Contains("true")))
                        asc = true;
                }
                if (asc)
                    list = list.OrderBy(s => s.EventDate);
                else
                    list = list.OrderByDescending(s => s.Id).OrderByDescending(s => s.EventDate);

                if (Request.IsAjaxRequest())
                    return PartialView(list);
                return View(list);
            }
            catch (ServerNotFoundException sEx)
            {
                return new HttpNotFoundResult(sEx.ToString());
            }
            catch (RobotNotFoundException rEx)
            {
                return new HttpNotFoundResult(rEx.ToString());
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public ActionResult Scheduling(int id, int serverId)
        {
            try
            {
                var item = FindRobot(serverId, id);
                IEnumerable<Schedule> list = item.Schedules;

                if (Request.IsAjaxRequest())
                    return PartialView(list);
                return View(list);
            }
            catch (ServerNotFoundException sEx)
            {
                return new HttpNotFoundResult(sEx.ToString());
            }
            catch (RobotNotFoundException rEx)
            {
                return new HttpNotFoundResult(rEx.ToString());
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public ActionResult Notification(int id, int serverId)
        {
            try
            {
                var item = FindRobot(serverId, id);
                //var notification = item.Notification;
                var notification = item.Notifier;

                if (Request.IsAjaxRequest())
                    return PartialView(notification);
                return View(notification);
            }
            catch (ServerNotFoundException sEx)
            {
                return new HttpNotFoundResult(sEx.ToString());
            }
            catch (RobotNotFoundException rEx)
            {
                return new HttpNotFoundResult(rEx.ToString());
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public ActionResult Normalization(int id, int serverId)
        {
            try
            {
                var item = FindRobot(serverId, id);

ParagonRCC-MVC3/ParagonRCC-MVC3/Views/Shared/Condition.cshtml
@model Paragon.RobotServices.Model.Condition

@{
    ViewBag.Title = "Condition";
}

@helper CondOption(int value, string text)
    {
    if (@Model.ConditionalId == value)
    {
        <option selected="selected" value="@value">@text</option>
    }
    else
    {
        <option value="@value">@text</option>
    }
}

@helper ConnOption(int value, string text)
    {
    if (@Model.ConnectorId == value)
    {
        <option selected="selected" value="@value">@text</option>
    }
    else
    {
        <option value="@value">@text</option>
    }
}

@*
<span class="container">
    <span>@Html.HiddenFor(c => c.Id)</span>
    <span>@Html.TextBoxFor(c => c.Operand1)</span>
    <span>@Html.ValidationMessageFor(c => c.Operand1)</span>
    <span>@Html.DropDownListFor(c => c.ConditionalId, (SelectList)ViewBag.Conditionals)</span>
    <span>@Html.ValidationMessageFor(c => c.ConditionalId)</span>
    <span>@Html.TextBoxFor(c => c.Operand2)</span>
    <span>@Html.ValidationMessageFor(c => c.Operand2)</span>
    <span>@Html.DropDownListFor(c => c.ConnectorId, (SelectList)ViewBag.Connectors)</span>
    <span>@Html.ValidationMessageFor(c => c.ConnectorId)</span>
</span>
*@
<tr>
    <td>
    <span class="id">@Model.ConditionId</span>
    </td>
    <td>
        <span>@Html.TextBoxFor(c => c.Operand1, new { @class = "operand1" })</span>
        <span>@Html.ValidationMessageFor(c => c.Operand1)</span>
    </td>
    <td>
        @*<span>@Html.DropDownListFor(c => c.ConditionalId, (SelectList)ViewBag.Conditionals, new { selected = @Model.ConditionalId})</span> *@
        <span><select class="conditional" name="conditional">
                @CondOption(1, "Equals")
                @CondOption(2, "NotEquals")
                @CondOption(3, "IsBlank")
                @CondOption(4, "IsNotBlank")
                @CondOption(5, "StartsWith")
                @CondOption(6, "EndsWith")
                @CondOption(7, "GreaterThan")
                @CondOption(8, "GreaterThanOrEqual")
                @CondOption(9, "LessThan")
                @CondOption(10, "LessThanOrEqual")
                @CondOption(11, "Contains")
                @CondOption(12, "InList")
                @CondOption(13, "NotInList")
                @CondOption(14, "Like")
                @CondOption(15, "NotLike")
                 </select></span>
        <span>@Html.ValidationMessageFor(c => c.ConditionalId)</span>
    </td>
    <td>
        <span>@Html.TextBoxFor(c => c.Operand2, new { @class = "operand2" })</span>
        <span>@Html.ValidationMessageFor(c => c.Operand2)</span>
    </td>
    <td>
        @*<span>@Html.DropDownListFor(c => c.ConnectorId, (SelectList)ViewBag.Connectors, new { selected = @Model.ConnectorId })</span> *@
        <span><select class="connector" name="connector">
                @ConnOption(1, "And")
                @ConnOption(2, "Or")
                 </select></span>
        <span>@Html.ValidationMessageFor(c => c.ConnectorId)</span>
    </td>
    <td title="drag to sort">
        <span class="ui-icon ui-icon-trash" title="Delete"></span>
        <span class="ui-icon ui-icon-copy" title="Copy" ></span>
    </td>
    @*<script type="text/javascript">
        $(function () {
            $("select[name='ConditionalId']").each(function () { $(this).val($(this)[0].attributes["selected"].value); });
            $("select[name='ConnectorId']").each(function () { $(this).val($(this)[0].attributes["selected"].value); });
            $("option").bind("click", function () { $(this).parent()[0].attributes["selected"].value = $(this)[0].attributes["value"].value });
        });
    </script>*@
</tr>

ParagonRCC-MVC3/ParagonRCC-MVC3/Views/Shared/Conditions.cshtml
@model IEnumerable<ParagonRCC_MVC3.Models.Condition>

@{
    ViewBag.Title = "Conditions";
}

<ol title="Conditions">
    <li>
        <span class="ui-helper-hidden">Id</span>
        <span>Operand1</span>
        <span>Conditional</span>
        <span>Operand2</span>
        <span>Connector</span>
    </li>
    @foreach (var item in Model)
    {
        <li>@Html.Partial("~/Views/Shared/Condition.cshtml", item)</li>
    }
</ol>

ParagonRCC-MVC3/ParagonRCC-MVC3/Views/Shared/GeneralLogon.cshtml
@{
    ViewBag.Title = "GeneralLogon";
}

<div class="logonForm">
<div class="headerLabel">GeneralLogon</div>

<div class="display-label">Provider:</div>
<div class="display-field">@Html.DropDownList("Providers", string.Empty)</div>

@foreach (string item in ViewBag.Fields)
{
    <div class="display-label">@item</div>
    <div class="display-field">@Html.TextBox(@item)</div>
}

</div>

ParagonRCC-MVC3/ParagonRCC-MVC3/Views/Shared/MappingGroupViewer.cshtml
@model ParagonRCC_MVC3.Models.MappingGroup

@{
    ViewBag.Title = "MappingGroupViewer";
}

<h2>MappingGroupViewer</h2>

<fieldset>
    <legend>@Model.Name</legend>
    @foreach (var item in Model.Mappings)
    {
        @Html.Partial("~/Views/Shared/MappingView.cshtml", item)
    }
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ParagonRCC-MVC3/ParagonRCC-MVC3/Views/Shared/MappingView.cshtml
@model ParagonRCC_MVC3.Models.Mapping

@{
    ViewBag.Title = "MappingView";
}

@using (Html.BeginForm("Mapping", "Robot", FormMethod.Post, new { }))
{
    <span class="display-label">Name</span>
    <span class="display-field">@Html.TextBox("name", @Model.Name)</span>
    @Html.Partial("~/Views/Shared/Conditions.cshtml", @Model.Conditions)
    @Html.Partial("~/Views/Shared/Transforms.cshtml", @Model.Transforms)
}

ParagonRCC-MVC3/ParagonRCC-MVC3/Views/Shared/Transform.cshtml
@model Paragon.RobotServices.Model.Field

@{
    ViewBag.Title = "Transform";
}

@*
<span class="container">
Transform
<span>@Html.HiddenFor(t => t.Id)</span>
<span>Name:</span>
<span>@Html.TextBoxFor(t => t.Name)</span>
<span>Value:</span>
<span>@Html.TextBoxFor(t => t.Value)</span>
</span>
*@

<tr>
    <td>
        <span class="id">@Model.FieldId</span> @* @Model.Id</span> *@
    </td>
    <td>
        <span>@Html.TextBox("name", Model.Name, new {@class = "name"})</span>
        <span>@Html.ValidationMessageFor(t => t.Name)</span>
    </td>
    <td>
        <span>@Html.TextBox("name", Model.Value, new {@class = "value"})</span>
        <span>@Html.ValidationMessageFor(t => t.Value)</span>
    </td>
    <td title="drag to sort">
        <span class="ui-icon ui-icon-trash" title="Delete"></span>
        <span class="ui-icon ui-icon-copy" title="Copy"></span>
    </td>
</tr>

ParagonRCC-MVC3/ParagonRCC-MVC3/Views/Shared/Transforms.cshtml
@model IEnumerable<ParagonRCC_MVC3.Models.Transform>

@{
    ViewBag.Title = "Transforms";
}

<ol title="Transforms">
    <li>
        <span class="ui-helper-hidden">Id</span>
        <span>Name</span>
        <span>Value</span>
    </li>
    @foreach (var item in Model)
    {
        <li>@Html.Partial("~/Views/Shared/Transform.cshtml", item)</li>
    }
</ol>

ParagonRCC-MVC3/ParagonRCC-MVC3/Views/Shared/_TreeView.cshtml
@using ParagonRCC_MVC3

@foreach (var s in ParagonRCC_MVC3.Models.Server.Servers)
{
    <div class="treeNodeSystem">
        <img alt="" class="treeSystemExpandImage" src="../../Content/images/tree/minus.gif" />
        @Html.ActionImage("~/Content/images/icon/WebServiceIcon.png", "Details", "Server", new { id = s.Id },
             s.Name + " : " + s.Host + ":" + s.Port, new { @class = "nodeLink" }, new { @class = "treeNodeIcon", alt = s.Name }, 
            new { @class = "treeNodeText" })
        <div class="nodeAdminRoot">
            @foreach (var r in s.Robots)
            {
            <div class="treeNode">
                <img class="treeExpandImage" alt="clear" src="../../Content/images/tree/clear9.gif" />
                <span class="treeLineVertical"></span>
                <span class="treeLineHorizontal"></span>
                @if (!object.ReferenceEquals(r, s.Robots[s.Robots.Count - 1]))
                {
                    <span class="treeLineVertToSibling"></span>
                }
                @{ string imgAlt = "";
                   string imgLoc = "";
                   switch (r.Status)
                   {
                       //case ParagonRCC_MVC3.Models.RobotStatus.Errors:
                       case "errors":
                           imgAlt = "PAS has encountered errors.  Please check the error logs.";
                           imgLoc = Url.Content("~/Content/images/icon/process_Errored.png");
                           break;
                       //case ParagonRCC_MVC3.Models.RobotStatus.Running:
                       case "running":
                           imgAlt = "PAS is running.";
                           imgLoc = Url.Content("~/Content/images/icon/process_Running.png");
                           break;
                       //case ParagonRCC_MVC3.Models.RobotStatus.Stopped:
                       case "stopped":
                           imgAlt = "PAS is stopped.";
                           imgLoc = Url.Content("~/Content/images/icon/process_Stopped.png");
                           break;
                       //case ParagonRCC_MVC3.Models.RobotStatus.Warnings:
                       case "warnings":
                           imgAlt = "PAS has encountered warnings.  Please check the error logs.";
                           imgLoc = Url.Content("~/Content/images/icon/process_warning.png");
                           break;
                   }
                }
                @Html.ActionImage(imgLoc, "Details", "Robot", new {id = r.Id, serverId = s.Id}, r.Name,
                    new {@class = "nodeLink"}, new { @class="treeNodeIcon", alt= imgAlt}, 
                    new {@class = "treeNodeText"})
            </div>
            }
        </div>
    </div>
}